spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/hotel_booking_db?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  data:
    initialize: ${APP_DATA_INITIALIZE:true}

logging:
  level:
    com.hotel: INFO